/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view.tela.locacao;

import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import locadora.controller.LocacaoController;
import locadora.model.Cliente;
import locadora.model.Veiculo;

/**
 *
 * @author Felipe
 */
public class JanelaLocacao extends javax.swing.JFrame {

    /**
     * Creates new form JanelaLocacao
     */
    public JanelaLocacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaLocacao1 = new locadora.view.tela.locacao.TabelaLocacao();
        formLocar1 = new locadora.view.tela.locacao.FormLocar();
        botaoVoltar1 = new locadora.view.tela.locacao.BotaoVoltar();
        formDados1 = new locadora.view.tela.locacao.FormDados();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formDados1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formLocar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tabelaLocacao1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabelaLocacao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(formLocar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private locadora.view.tela.locacao.BotaoVoltar botaoVoltar1;
    private locadora.view.tela.locacao.FormDados formDados1;
    private locadora.view.tela.locacao.FormLocar formLocar1;
    private locadora.view.tela.locacao.TabelaLocacao tabelaLocacao1;
    // End of variables declaration//GEN-END:variables

    public void setController(LocacaoController controller) {
        formDados1.setController(controller);
        botaoVoltar1.setController(controller); 
        formLocar1.setController(controller);
    }

    public void initView() {
        tabelaLocacao1.setJanelaView(this);
        java.awt.EventQueue.invokeLater(() ->  this.setVisible(true));
    }
    
    public void apresentaErro(String erro) {
       JOptionPane.showMessageDialog(null,erro + "\n", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    
    public void apresentaInfo(String info) {
        JOptionPane.showMessageDialog(null,info + "\n", "Informação", JOptionPane.INFORMATION_MESSAGE);
    }

    public void setClientFormView(Cliente cliente) {
        formDados1.setCliente(cliente);
    }
    
    public Cliente getClienteFormView(){
        return this.formDados1.getCliente();
    }
    
    public Veiculo getVeiculoParaLocarDaTabelaView() {
       return this.tabelaLocacao1.getVeiculoParaLocarDaTabela();
    }
        
    public void excluirVeiculoView(Veiculo veiculo) {
       tabelaLocacao1.excluirVeiculosDaTabela(veiculo);
    }
    
    public void mostrarListaVeiculosView(List<Veiculo> lista) {
        tabelaLocacao1.setListaVeiculosTabela(lista);
    }
    
    public String getAtributoFormView() {
        return this.formDados1.getAtributo();
    }

    public String getCategoriaFormView() {
        return this.formDados1.getCategoria();
    }
    
    public String getMarcaFormView() {
        return this.formDados1.getMarca();
    }
    
    public String getCpfClienteFormView() {
        return this.formDados1.getClienteCpf();
    }

    public String getNomeClienteFormView() {
        return this.formDados1.getClienteNome();
    }
    
    public String getSobrenomeClienteFormView() {
        return this.formDados1.getClienteSobrenome();
    }
    
    public int getDiaFormView(){
        return this.formLocar1.getDia();
    }
    
    public Calendar getDataFormView(){
        return this.formLocar1.getDataLocacao();
    }

    public void limparFormClienteView() {
        formDados1.limparForm();
    }
}
