/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.tela.devolucao;

import java.util.List;
import javax.swing.JTable;
import locadora.model.Veiculo;

/**
 *
 * @author Felipe
 */
public class TabelaDevolucao extends javax.swing.JPanel {
    
    private DevolucaoTableModel devolucaoTableModel = new DevolucaoTableModel();
    private JanelaDevolucao janela;
    private int linhaClicadaParaAtualizacao = -1;
    /**
     * Creates new form TabelaDevolucao
     */
    public TabelaDevolucao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlDevolucao = new javax.swing.JScrollPane();
        tblDevolucao = new javax.swing.JTable();

        tblDevolucao.setModel(devolucaoTableModel);
        scrlDevolucao.setViewportView(tblDevolucao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTabelaDevolucao() {
        return tblDevolucao;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrlDevolucao;
    private javax.swing.JTable tblDevolucao;
    // End of variables declaration//GEN-END:variables

    void setJanelaView(JanelaDevolucao janela) {
        this.janela = janela;
    }
    
    public void inserirVeiculoTabela(Veiculo veiculo) {
        devolucaoTableModel.adicionaVeiculo(veiculo);
    }

    public void setListaVeiculosTabela(List<Veiculo> lista) {
        devolucaoTableModel.setListaVeiculo(lista);
    }
    
    public Veiculo getVeiculoParaLocarDaTabela() {
        int linhaSelecionada = this.getTabelaDevolucao().getSelectedRow();
            Veiculo veiculo = devolucaoTableModel.getVeiculo(linhaSelecionada);
        return veiculo;
    }
    
    public void excluirVeiculosDaTabela(Veiculo veiculo) {
        devolucaoTableModel.removeVeiculo(veiculo);
    }
    
    public void atualizarVeiculoNaTabela(Veiculo veiculo) {
        devolucaoTableModel.fireTableRowsUpdated(linhaClicadaParaAtualizacao, linhaClicadaParaAtualizacao);    
    }  
}
