/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view.tela.vendas;

import locadora.controller.VendasController;
import locadora.model.enums.Categoria;
import locadora.model.enums.Marca;


/**
 *
 * @author Felipe
 */
public class FormPesquisar extends javax.swing.JPanel {

    /**
     * Creates new form BotaoPesquisar
     */
    public FormPesquisar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPesquisar = new javax.swing.JButton();
        cbxPesquisa = new javax.swing.JComboBox<>();
        cbxFiltro = new javax.swing.JComboBox<>();

        btnPesquisar.setText("Pesquisar");

        cbxPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Categoria", "Marca", " " }));
        cbxPesquisa.setSelectedItem(cbxPesquisa);
        cbxPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbxFiltro, 0, 152, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPesquisaActionPerformed
        try{
            if(cbxPesquisa.getSelectedItem().equals("Tipo")){
                cbxFiltro.removeAllItems();
                cbxFiltro.addItem("Automovel");
                cbxFiltro.addItem("Motocicleta");
                cbxFiltro.addItem("Van");
            }
            else
            if(cbxPesquisa.getSelectedItem().equals("Categoria")){
                cbxFiltro.removeAllItems();
                cbxFiltro.addItem(Categoria.POPULAR.toString());
                cbxFiltro.addItem(Categoria.INTERMEDIARIO.toString());
                cbxFiltro.addItem(Categoria.LUXO.toString());
            }
            else
            if(cbxPesquisa.getSelectedItem().equals("Marca")) {
                cbxFiltro.removeAllItems();
                cbxFiltro.addItem(Marca.Fiat.toString());
                cbxFiltro.addItem(Marca.GM.toString());
                cbxFiltro.addItem(Marca.Honda.toString());
                cbxFiltro.addItem(Marca.Mercedes.toString());
                cbxFiltro.addItem(Marca.Volkswagen.toString());
            }
            else
                cbxFiltro.removeAllItems();
                
        } catch (Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_cbxPesquisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbxFiltro;
    private javax.swing.JComboBox<String> cbxPesquisa;
    // End of variables declaration//GEN-END:variables
    
    public void setController(VendasController controller) {
        this.btnPesquisar.addActionListener(e -> controller.pesquisarVeiculo());
    } 
    
    public String getPesquisa(){
        return cbxPesquisa.getSelectedItem().toString();
    }
    
    public String getFiltro(){
        String filtro;
        if(cbxFiltro.getSelectedItem().toString() == null)
            filtro = "VAZIO";
        else
            filtro = cbxFiltro.getSelectedItem().toString();
        
        return filtro;
    }
}
