/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view;

import locadora.controller.ClienteController;

/**
 *
 * @author Felipe
 */
public class BotoesClientes extends javax.swing.JPanel {

    /**
     * Creates new form BotoesClientes
     */
    public BotoesClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIncluirCliente = new javax.swing.JButton();
        btnAtualizarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        btnListarCliente = new javax.swing.JButton();

        btnIncluirCliente.setText("Incluir");

        btnAtualizarCliente.setText("Atualizar");

        btnExcluirCliente.setText("Excluir");

        btnListarCliente.setText("Listar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnIncluirCliente)
                .addGap(18, 18, 18)
                .addComponent(btnAtualizarCliente)
                .addGap(18, 18, 18)
                .addComponent(btnExcluirCliente)
                .addGap(18, 18, 18)
                .addComponent(btnListarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirCliente)
                    .addComponent(btnAtualizarCliente)
                    .addComponent(btnExcluirCliente)
                    .addComponent(btnListarCliente))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarCliente;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnIncluirCliente;
    private javax.swing.JButton btnListarCliente;
    // End of variables declaration//GEN-END:variables

    public void setController(ClienteController controller) {
      
        this.btnIncluirCliente.addActionListener(e -> controller.incluirCliente());
        this.btnAtualizarCliente.addActionListener(e -> controller.atualizarCliente());
        this.btnExcluirCliente.addActionListener(e -> controller.excluirCliente());
        this.btnListarCliente.addActionListener(e -> controller.listarCliente());

    }
}
