/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package locadora.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import locadora.model.Cliente;

/**
 *
 * @author Felipe
 */
public class TabelaClientes extends javax.swing.JPanel {
    private ClientesTableModel modeloTabelaCliente = new ClientesTableModel();;
    private JanelaClientes janela;
    private int linhaClicadaParaAtualizacao = -1;
    /**
     * Creates new form TabelaClientes
     */
    public TabelaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();

        tabelaClientes.setModel(modeloTabelaCliente);
        tabelaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClientesMouseClicked

        linhaClicadaParaAtualizacao = this.tabelaClientes.rowAtPoint(evt.getPoint());
        Cliente cliente = modeloTabelaCliente.getCliente(linhaClicadaParaAtualizacao);
        janela.getFormularioClientesView().setCliente(cliente);
    }//GEN-LAST:event_tabelaClientesMouseClicked

    public JTable getTabelaClientes() {
        return tabelaClientes;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables

public void setJanelaView(JanelaClientes janela) {
        this.janela = janela;
    }
    
    public void inserirClienteTabela(Cliente cliente) {
        modeloTabelaCliente.adicionaCliente(cliente);
    }

    public void setListaClientesTabela(List<Cliente> lista) {
        modeloTabelaCliente.setListaCliente(lista);
    }
    
    public List<Cliente> getClientesParaExcluirDaTabela() {
        int[] linhasSelecionadas = this.getTabelaClientes().getSelectedRows();
        List<Cliente> listaExcluir = new ArrayList();
        for (int i = 0; i < linhasSelecionadas.length; i++) {
            Cliente cliente = modeloTabelaCliente.getCliente(linhasSelecionadas[i]);
            listaExcluir.add(cliente);
        }
        return listaExcluir;
    }
    
    public void excluirClientesDaTabela(List<Cliente> listaParaExcluir) {
        modeloTabelaCliente.removeClientes(listaParaExcluir);
    }

    public void atualizarClienteNaTabela(Cliente cliente) {
        
        modeloTabelaCliente.fireTableRowsUpdated(linhaClicadaParaAtualizacao, linhaClicadaParaAtualizacao);
        
    }    
}
